name: Flutter Deploy
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - roadtrips
jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5'
    - run: flutter pub get
      working-directory: roadtrips/
    - run: flutter build apk
      working-directory: roadtrips/
    - name: version
      run: echo "::set-output name=version::`date -u +"%Y-%m-%d-%H_%M_%S"`-`git rev-parse HEAD`"
      id: version
      working-directory: ./
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./roadtrips/build/app/outputs/flutter-apk/app-release.apk
        asset_name: app-release.apk
        asset_content_type: application/octet-stream